style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/uzimaru0000/tv
options:
  commits:
    filters:
      Type:
        - sparkles
        - bug
        - horse
        - recycle
  commit_groups:
    title_maps:
      sparkles: Features
      bug: Bug Fixes
      horse: Performance Improvements
      recycle: Code Refactoring
  header:
    pattern: "^:(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
